// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package proto_user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	RegisterRequest
	RegisterResponse
	LoginRequest
	LoginResponse
	UserInfoRequest
	UserInfoResponse
*/
package proto_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterRequest struct {
	UserName  string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	Password  string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LoginRequest struct {
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	IsSuccess bool `protobuf:"varint,1,opt,name=is_success,json=isSuccess" json:"is_success,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

type UserInfoRequest struct {
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
}

func (m *UserInfoRequest) Reset()                    { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()               {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserInfoRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type UserInfoResponse struct {
	UserId    int64  `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UserName  string `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
}

func (m *UserInfoResponse) Reset()                    { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()               {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserInfoResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfoResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfoResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "proto.user.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "proto.user.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "proto.user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "proto.user.LoginResponse")
	proto.RegisterType((*UserInfoRequest)(nil), "proto.user.UserInfoRequest")
	proto.RegisterType((*UserInfoResponse)(nil), "proto.user.UserInfoResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4f, 0x83, 0x40,
	0x10, 0xc5, 0x0b, 0x68, 0x0b, 0xa3, 0xa6, 0xcd, 0x5e, 0x44, 0x6a, 0x13, 0xb3, 0x27, 0x0f, 0x66,
	0x0f, 0x7a, 0xf7, 0x4a, 0x6a, 0x8c, 0x07, 0x8c, 0xe7, 0x06, 0xcb, 0x94, 0xec, 0x01, 0x16, 0x77,
	0x20, 0x7e, 0x58, 0xbf, 0x8c, 0x61, 0x01, 0xf9, 0x93, 0xc6, 0xf4, 0x44, 0x66, 0xde, 0xcc, 0xfc,
	0x1e, 0x6f, 0x01, 0x2a, 0x42, 0x2d, 0x0a, 0xad, 0x4a, 0xc5, 0xc0, 0x7c, 0x44, 0xdd, 0xe1, 0x12,
	0x96, 0x11, 0xa6, 0x92, 0x4a, 0xd4, 0x11, 0x7e, 0x55, 0x48, 0x25, 0x5b, 0x83, 0x57, 0x4b, 0xbb,
	0x3c, 0xce, 0xd0, 0xb7, 0xee, 0xac, 0x7b, 0x2f, 0x72, 0xeb, 0xc6, 0x5b, 0x9c, 0x21, 0xdb, 0x00,
	0x1c, 0xa4, 0xa6, 0xb2, 0x51, 0x6d, 0xa3, 0x7a, 0xa6, 0x63, 0xe4, 0x00, 0xdc, 0x22, 0x26, 0xfa,
	0x56, 0x3a, 0xf1, 0x9d, 0x66, 0xb5, 0xab, 0xf9, 0x03, 0xac, 0x7a, 0x14, 0x15, 0x2a, 0x27, 0x64,
	0x3e, 0x2c, 0x32, 0x24, 0x8a, 0xd3, 0x8e, 0xd4, 0x95, 0x3c, 0x84, 0xcb, 0x57, 0x95, 0xca, 0xfc,
	0x24, 0x57, 0x43, 0xac, 0x3d, 0xc1, 0x0a, 0xb8, 0x6a, 0x0f, 0xb5, 0xcc, 0x0d, 0x80, 0xa4, 0x1d,
	0x55, 0xfb, 0x3d, 0x12, 0x99, 0x53, 0x6e, 0xe4, 0x49, 0x7a, 0x6f, 0x1a, 0x5c, 0xc0, 0xf2, 0x83,
	0x50, 0x6f, 0xf3, 0x83, 0x3a, 0x85, 0xcd, 0x53, 0x58, 0xf5, 0xf3, 0x2d, 0xe2, 0x1a, 0x16, 0x66,
	0x41, 0x26, 0x66, 0xdc, 0x89, 0xe6, 0x75, 0xb9, 0x4d, 0xc6, 0x97, 0xec, 0x7f, 0xb3, 0x75, 0x26,
	0xd9, 0x3e, 0xfe, 0x58, 0x70, 0x56, 0x93, 0x58, 0x08, 0x6e, 0x17, 0x24, 0x5b, 0x8b, 0xfe, 0x31,
	0xc5, 0xe4, 0x25, 0x83, 0xdb, 0xe3, 0x62, 0x63, 0x92, 0xcf, 0xd8, 0x33, 0x9c, 0x9b, 0x68, 0x98,
	0x3f, 0x1c, 0x1c, 0xc6, 0x1e, 0xdc, 0x1c, 0x51, 0xfe, 0xf6, 0x5f, 0xe0, 0x22, 0xc4, 0xb2, 0xfb,
	0xfb, 0xb1, 0x97, 0x49, 0x86, 0x63, 0x2f, 0xd3, 0xc0, 0xf8, 0xec, 0x73, 0x6e, 0xe4, 0xa7, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xba, 0x77, 0xc2, 0x1f, 0xa9, 0x02, 0x00, 0x00,
}
